/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar áreas */
        get: operations["getAreas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/floor-layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener snapshot del floor */
        get: operations["getFloorLayout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar mesas */
        get: operations["listTables"];
        put?: never;
        /**
         * Crear mesa (solo áreas no VIP)
         * @description Máximo 8 mesas por área no VIP.
         */
        post: operations["createTable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{id}/position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar posición de mesa
         * @description Soporta control de concurrencia con expectedVersion.
         */
        patch: operations["updateTablePosition"];
        trace?: never;
    };
    "/tables/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Liberar mesa (marca reserva activa como completed) */
        post: operations["releaseTable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar reservas por fecha */
        get: operations["listReservations"];
        put?: never;
        /**
         * Crear reserva
         * @description Requiere Idempotency-Key para evitar duplicados.
         */
        post: operations["createReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambiar estado de reserva */
        patch: operations["updateReservationStatus"];
        trace?: never;
    };
    "/walkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear ocupación walk-in */
        post: operations["createWalkin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar disponibilidad */
        get: operations["getAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            code: string;
            message: string;
            details?: unknown;
        };
        Area: {
            id: string;
            /** @enum {string} */
            name: "Terraza" | "Patio" | "Lobby" | "Bar" | "Salones VIP";
            maxTables: number;
        };
        /** @enum {string} */
        TableType: "standard" | "square" | "circular";
        /** @enum {string} */
        ReservationStatus: "pending" | "confirmed" | "cancelled" | "completed" | "no_show";
        RestaurantTable: {
            id: string;
            areaId: string;
            capacity: number;
            type: components["schemas"]["TableType"];
            name: string;
            isVIP: boolean;
            canMerge: boolean;
            mergeGroup: string | null;
            x: number;
            y: number;
            version?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        Reservation: {
            id: string;
            tableIds: string[];
            clientName: string;
            partySize: number;
            date: string;
            startTime: string;
            endTime: string;
            status: components["schemas"]["ReservationStatus"];
            duration: number;
            notes: string;
        };
        CreateReservationInput: {
            tableIds: string[];
            clientName: string;
            partySize: number;
            date: string;
            startTime: string;
            endTime: string;
            status: components["schemas"]["ReservationStatus"];
            duration: number;
            notes: string;
        };
        CreateWalkInInput: {
            tableId: string;
            clientName?: string;
            partySize?: number;
            notes?: string;
        };
        CreateTableInput: {
            areaId: string;
            /** @enum {integer} */
            capacity?: 2 | 4 | 6 | 8;
            /** @enum {string} */
            type?: "standard" | "square";
        };
        UpdateTablePositionInput: {
            x: number;
            y: number;
            expectedVersion?: number;
            areaId?: string;
            canvasWidth?: number;
            canvasHeight?: number;
            isMergedView?: boolean;
        };
        AvailabilitySuggestion: {
            tableIds: string[];
            capacity: number;
            tableName: string;
        };
        AvailabilityResponse: {
            suggestedTables: components["schemas"]["AvailabilitySuggestion"][];
            alternatives: components["schemas"]["AvailabilitySuggestion"][];
        };
        FloorLayoutResponse: {
            date: string;
            areaId: string | null;
            areas: components["schemas"]["Area"][];
            tables: components["schemas"]["RestaurantTable"][];
            reservations: components["schemas"]["Reservation"][];
        };
    };
    responses: {
        /** @description Error de validación */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflicto de negocio o solape */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflicto de concurrencia */
        ConcurrencyError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API saludable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example table-master-api */
                        service?: string;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getAreas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de áreas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Area"][];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getFloorLayout: {
        parameters: {
            query?: {
                /** @description Fecha YYYY-MM-DD */
                date?: string;
                areaId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot con áreas, mesas y reservas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorLayoutResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listTables: {
        parameters: {
            query?: {
                areaId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de mesas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantTable"][];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    createTable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTableInput"];
            };
        };
        responses: {
            /** @description Mesa creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantTable"];
                };
            };
            409: components["responses"]["ConflictError"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateTablePosition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTablePositionInput"];
            };
        };
        responses: {
            /** @description Mesa actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantTable"];
                };
            };
            409: components["responses"]["ConcurrencyError"];
            422: components["responses"]["ValidationError"];
        };
    };
    releaseTable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado de liberación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        released?: boolean;
                        reservation?: components["schemas"]["Reservation"];
                    };
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listReservations: {
        parameters: {
            query: {
                date: string;
                areaId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reservas filtradas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"][];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    createReservation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservationInput"];
            };
        };
        responses: {
            /** @description Reserva creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            409: components["responses"]["ConflictError"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateReservationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["ReservationStatus"];
                };
            };
        };
        responses: {
            /** @description Reserva actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    createWalkin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWalkInInput"];
            };
        };
        responses: {
            /** @description Walk-in creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            409: components["responses"]["ConflictError"];
            422: components["responses"]["ValidationError"];
        };
    };
    getAvailability: {
        parameters: {
            query: {
                date: string;
                partySize: number;
                startTime: string;
                areaPreference?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sugerencias de disponibilidad */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
}
